reformat code

diff --git a/bin/docker-ratelimit-list b/bin/docker-ratelimit-list
--- a/bin/docker-ratelimit-list
+++ b/bin/docker-ratelimit-list
@@ -12,7 +12,7 @@ function get_limits() {
   local headers
 
   if [[ "$#" -eq 1 ]]; then
-    >&2 echo "Error: missing password"
+    echo >&2 "Error: missing password"
     return 1
   fi
 
@@ -28,9 +28,9 @@ function get_limits() {
   ratelimits=$(echo "$headers" | grep "^RateLimit-")
 
   echo -n "{"
-  echo -n "$ratelimits" \
-    | awk '{ printf "%s", tolower(gensub(/^RateLimit-([^:]+): ([0-9]+);w=([0-9]+).*$/, "\"\\1\":{\"value\": \\2, \"interval\": \\3},", "g", $0)) }' \
-    | head -c-1
+  echo -n "$ratelimits" |
+    awk '{ printf "%s", tolower(gensub(/^RateLimit-([^:]+): ([0-9]+);w=([0-9]+).*$/, "\"\\1\":{\"value\": \\2, \"interval\": \\3},", "g", $0)) }' |
+    head -c-1
   echo -n "}"
 }
 
@@ -38,7 +38,7 @@ user=""
 pass=""
 
 if [[ "$#" -eq 1 ]]; then
-  >&2 echo "Error: missing password"
+  echo >&2 "Error: missing password"
   exit 1
 fi
 
diff --git a/bin/docker-volume-import b/bin/docker-volume-import
--- a/bin/docker-volume-import
+++ b/bin/docker-volume-import
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-getFullPath () {
+getFullPath() {
   local SRC=${1}
-  if [ -z "`which readlink 2>/dev/null`" ]; then
-    realpath ${SRC};
+  if [ -z "$(which readlink 2>/dev/null)" ]; then
+    realpath ${SRC}
   else
-    readlink -f ${SRC};
+    readlink -f ${SRC}
   fi
 }
 
@@ -19,8 +19,8 @@ VOL_DST_CHECK=$(docker volume ls -q -f name="^${VOL_DST}$")
 VOL_SRC_CHECK=$(ls ${VOL_SRC} 2>/dev/null)
 
 if [ "${VOL_SRC}" != "${VOL_SRC_CHECK}" ]; then
-   >&2 echo 'File not found: "'${VOL_SRC}'"';
-   exit 1;
+  echo >&2 'File not found: "'${VOL_SRC}'"'
+  exit 1
 fi
 
 echo -n '"'${VOL_SRC}'" will be imported to volume "'${VOL_DST}'" [y/N] '
@@ -29,15 +29,15 @@ read ANSWER
 
 if [ "${ANSWER}" != "y" ]; then
   echo 'Canceled'
-  exit 0;
+  exit 0
 fi
 
 if [ "${VOL_DST}" == "${VOL_DST_CHECK}" ]; then
   echo -n 'Destination volume "'${VOL_DST}'" already exists. It will be overwritten. [y/N] '
   read ANSWER
   if [ "${ANSWER}" != "y" ]; then
-    echo 'Canceled';
-    exit 0;
+    echo 'Canceled'
+    exit 0
   fi
   docker volume rm ${VOL_DST}
 fi
